highlander_says:
    path: /highlander-says/{threshold<\d+>?50}
    controller: App\Controller\WeatherController::highlanderSays
    # defaults:
    #     threshold: 50
    # requirements: 
    #     threshold: \d+

highlander_says_guess:
    path: /highlander-says/{guess}
    controller: App\Controller\WeatherController::highlanderSaysGuess

# forecast:
#     path: /{country_code<ES|FR|DE>}/{city_name<Barcelona|Paris|Berlin>}
#     controller: App\Controller\WeatherController::forecast


